version: "3.9"

services:
  snapmaker-u1-discord:
    build: .
    container_name: snapmaker-u1-discord
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./printers.json:/app/printers.json
    network_mode: "host"
